name: polytech
description: "Polytech is a School Management System"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version: 1.0.1+6 #for Android
version: 1.0.0+0 #for iOS

environment:
  sdk: ^3.8.1

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  hugeicons: ^0.0.11
  flutter_secure_storage: ^8.1.0
  http: ^1.5.0
  flutter_svg: ^2.2.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  url_launcher: ^6.3.2
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^5.0.0


flutter:


  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/

